# The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
# Let us list the factors of the first seven triangle numbers:

#  1: 1
#  3: 1,3
#  6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28

# We can see that 28 is the first triangle number to have over five divisors.
# What is the value of the first triangle number to have over five hundred divisors?



import math


def numOfFactors(num):
  result = 0
  for i in range (1,round(math.sqrt(num))+1):
    if num%i == 0:
      result += 2
    if i*i ==num:
      result = result - 1
  return (result)

print ('running')

currentNum = 0
increment = 1
stop = 0

while stop == 0:
  currentNum += increment
  increment +=1
  x = numOfFactors(currentNum)
  if x > 100:
    print (x, currentNum)
  if x > 500:
    stop == 1
    print(currentNum, x)
    break
