# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.




prevnum=1
currnum=1
checkingn=0
trn=0
while checkingn<4000000:
  prevnum=currnum
  currnum=checkingn
  if checkingn%2==0:
    trn=trn+checkingn
    print (trn)
  checkingn=prevnum+currnum